//! Read-only Add-in Manager returns, independent of an add-in generation.
//!
//! Excel reads these static values while it owns the loaded XLL. Neither root
//! nor string has a free bit: there is no return obligation or xlAutoFree12
//! callback, and no data may be retained past physical module unload.

use crate::ingress::ExportIngress;
use xlfn_sys::{XLOPER12, XLOPER12Value, XLTYPE_INT, XLTYPE_NUM, XLTYPE_STR};

struct StaticReturn(XLOPER12);

// SAFETY: The only constructors select either a scalar error or a string
// backed by an immutable static slice. The root and its payload are never
// mutated, including through Excel's read-only static-return ABI contract.
unsafe impl Sync for StaticReturn {}

impl StaticReturn {
    fn pointer(&'static self) -> *mut XLOPER12 {
        std::ptr::from_ref(&self.0).cast_mut()
    }
}

static INVALID_ACTION: StaticReturn = StaticReturn(XLOPER12::error(xlfn_sys::XLERR_VALUE));

pub(crate) fn invalid_action_pointer() -> *mut XLOPER12 {
    INVALID_ACTION.pointer()
}

/// Immutable metadata generated by `#[excel_addin]`.
#[doc(hidden)]
pub struct AddinMetadata {
    name: StaticReturn,
}

impl AddinMetadata {
    /// Constructs the name from a counted UTF-16 literal emitted by the macro.
    #[doc(hidden)]
    pub const fn new(counted_name: &'static [u16]) -> Self {
        assert!(
            !counted_name.is_empty(),
            "metadata name needs a length unit"
        );
        assert!(
            counted_name[0] as usize == counted_name.len() - 1,
            "metadata name length must match its UTF-16 payload"
        );
        assert!(
            counted_name.len() - 1 <= crate::utf16::EXCEL_STRING_LIMIT,
            "metadata name exceeds Excel's string limit"
        );
        Self {
            name: StaticReturn(XLOPER12 {
                value: XLOPER12Value {
                    string: counted_name.as_ptr().cast_mut(),
                },
                xltype: XLTYPE_STR,
            }),
        }
    }

    /// Reads the action without runtime state or Excel callbacks.
    ///
    /// # Safety
    /// `action` is null or points to the live XLOPER12 supplied by Excel.
    pub(crate) unsafe fn query(&'static self, action: *mut XLOPER12) -> *mut XLOPER12 {
        // SAFETY: Excel supplies a live action for the duration of this call.
        let Some(action) = (unsafe { action.as_ref() }) else {
            return invalid_action_pointer();
        };
        let asks_for_name = match action.base_type() {
            // SAFETY: These numeric tags select the corresponding union member.
            XLTYPE_INT => unsafe { action.value.integer == 1 },
            // SAFETY: XLTYPE_NUM selects the number union member.
            XLTYPE_NUM => unsafe { action.value.number == 1.0 },
            _ => false,
        };
        if asks_for_name {
            self.name.pointer()
        } else {
            invalid_action_pointer()
        }
    }
}

pub(crate) fn metadata_boundary(operation: impl FnOnce() -> *mut XLOPER12) -> *mut XLOPER12 {
    with_metadata_entry(crate::module_runtime::ingress(), operation)
}

fn with_metadata_entry(
    ingress: &ExportIngress,
    operation: impl FnOnce() -> *mut XLOPER12,
) -> *mut XLOPER12 {
    // Opening/closing entries still own a reservation and must keep it until
    // the metadata read finishes. Closed entries own no generation resources;
    // their static reads rely on Excel's existing loaded-module call contract.
    let _entry = ingress.enter_with(|| {});
    operation()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ingress::{PHASE_CLOSED, PHASE_CLOSING, PHASE_OPEN, PHASE_OPENING};
    use std::sync::{Arc, mpsc};
    use std::time::Duration;

    static NAME: AddinMetadata = AddinMetadata::new(&[4, 0x540d, 0x524d, 0xd83d, 0xde80]);

    fn query(action: &mut XLOPER12) -> *mut XLOPER12 {
        // SAFETY: The action is a live value and NAME is immutable static data.
        unsafe { NAME.query(action) }
    }

    fn assert_name(pointer: *mut XLOPER12) {
        // SAFETY: NAME owns this static root and its counted UTF-16 buffer.
        let value = unsafe { &*pointer };
        assert_eq!(value.xltype, XLTYPE_STR);
        // SAFETY: The string tag selects the immutable counted name.
        let string = unsafe { value.value.string };
        // SAFETY: The static name contains its length unit and four payload units.
        let units = unsafe { std::slice::from_raw_parts(string, 5) };
        assert_eq!(units, &[4, 0x540d, 0x524d, 0xd83d, 0xde80]);
    }

    #[test]
    fn metadata_name_and_error_roots_remain_independent_without_free_callbacks() {
        let name = query(&mut XLOPER12::integer(1));
        assert_eq!(query(&mut XLOPER12::number(1.0)), name);
        for mut action in [
            XLOPER12::integer(0),
            XLOPER12::number(1.5),
            XLOPER12::number(f64::NAN),
            XLOPER12::number(f64::INFINITY),
            XLOPER12::error(xlfn_sys::XLERR_NA),
            XLOPER12::nil(),
            XLOPER12::missing(),
            XLOPER12::boolean(true),
        ] {
            let error = query(&mut action);
            assert_ne!(error, name);
            // SAFETY: INVALID_ACTION is a live immutable static error root.
            let value = unsafe { &*error };
            assert_eq!(value.xltype, xlfn_sys::XLTYPE_ERR);
            // SAFETY: XLTYPE_ERR selects the error union member.
            assert_eq!(unsafe { value.value.error }, xlfn_sys::XLERR_VALUE);
            assert_name(name);
        }
        // SAFETY: The metadata query explicitly tolerates a null action.
        let null_action = unsafe { NAME.query(std::ptr::null_mut()) };
        assert_eq!(null_action, invalid_action_pointer());

        std::thread::scope(|scope| {
            for _ in 0..8 {
                scope.spawn(|| {
                    for _ in 0..100 {
                        assert_name(query(&mut XLOPER12::integer(1)));
                        assert_eq!(query(&mut XLOPER12::integer(2)), invalid_action_pointer());
                    }
                });
            }
        });
        assert_name(name);
    }

    #[test]
    fn metadata_reads_in_every_ingress_phase_without_opening_admission() {
        let ingress = ExportIngress::new();
        let read = |phase, active| {
            let pointer = with_metadata_entry(&ingress, || {
                assert_eq!(ingress.phase(), phase);
                assert_eq!(ingress.active_calls(), active);
                query(&mut XLOPER12::integer(1))
            });
            assert_name(pointer);
            assert_eq!(ingress.phase(), phase);
            assert_eq!(ingress.active_calls(), 0);
        };
        read(PHASE_CLOSED, 0);
        ingress.begin_opening();
        read(PHASE_OPENING, 1);
        ingress.complete_open(|| Ok::<(), ()>(())).unwrap().unwrap();
        read(PHASE_OPEN, 1);
        ingress.begin_close_with(|| {});
        read(PHASE_CLOSING, 1);
        ingress.seal_and_drain().unwrap();
        read(PHASE_CLOSED, 0);
    }

    #[test]
    fn generated_metadata_path_reads_cold_open_and_closed_runtime_without_return_obligations() {
        let _module_lease = crate::ingress::acquire_test_module_lease();
        let fixture = crate::runtime::StaticTestRuntime::<()>::new();
        let runtime = fixture.runtime();
        let read = |phase| {
            // SAFETY: This stack action is live throughout the metadata call.
            let pointer = unsafe {
                crate::__private::v1::addin_manager_info(&NAME, &mut XLOPER12::integer(1))
            };
            assert_name(pointer);
            assert_eq!(runtime.phase(), phase);
            assert_eq!(runtime.return_tracker().outstanding_obligations(), 0);
        };
        // A never-opened runtime starts Closed, with ingress epoch zero.
        read(crate::lifecycle::LifecyclePhase::Closed);
        let opening = runtime.begin_open().unwrap();
        let mut opening = runtime.publish(opening, (), ());
        runtime.finish_open(&mut opening, Vec::new()).unwrap();
        drop(opening);
        read(crate::lifecycle::LifecyclePhase::Open);
        assert_eq!(crate::boundary::host::host_auto_remove(runtime), 1);
        read(crate::lifecycle::LifecyclePhase::Closed);
    }

    #[test]
    fn closing_waits_for_a_metadata_read_before_sealing() {
        let ingress = Arc::new(ExportIngress::new());
        ingress.begin_opening();
        ingress.complete_open(|| Ok::<(), ()>(())).unwrap().unwrap();
        let (entered_tx, entered_rx) = mpsc::sync_channel(0);
        let (release_tx, release_rx) = mpsc::sync_channel(0);
        let reading = Arc::clone(&ingress);
        let reader = std::thread::spawn(move || {
            let pointer = with_metadata_entry(&reading, || {
                entered_tx.send(()).unwrap();
                release_rx.recv().unwrap();
                query(&mut XLOPER12::integer(1))
            });
            assert_name(pointer);
        });
        entered_rx.recv().unwrap();
        ingress.begin_close_with(|| {});
        let draining = Arc::clone(&ingress);
        let (drained_tx, drained_rx) = mpsc::sync_channel(0);
        let closer = std::thread::spawn(move || {
            draining.seal_and_drain().unwrap();
            drained_tx.send(()).unwrap();
        });
        assert!(drained_rx.recv_timeout(Duration::from_millis(20)).is_err());
        release_tx.send(()).unwrap();
        drained_rx.recv_timeout(Duration::from_secs(1)).unwrap();
        reader.join().unwrap();
        closer.join().unwrap();
        assert_eq!(ingress.phase(), PHASE_CLOSED);
    }
}
