[package]
name = "xlfn-windows-bindings-gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
windows-bindgen.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"
linker_messages = "deny"
dead_code_pub_in_binary = "deny"
dangling_pointers_from_locals = "deny"
integer_to_ptr_transmutes = "deny"

[lints.clippy]
allow_attributes_without_reason = "deny"
dbg_macro = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
