[package]
name = "xlfn-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
description = "Implementation-only ownership and concurrency primitives for xlfn"

[dependencies]
arc-swap.workspace = true
parking_lot.workspace = true
triomphe.workspace = true

[dev-dependencies]
static_assertions.workspace = true

[lints]
workspace = true
